#!/bin/sh

set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

if [ -d "$ROOT_DIR/Exchange/Resources/Schemes" ]; then
  APP_DIR="$ROOT_DIR/Exchange"
else
  APP_DIR="$ROOT_DIR/exchange"
fi

SCHEMES_DIR="$APP_DIR/Resources/Schemes"
BUILD_DIR="$APP_DIR/Resources/Build"
BUILD_BRAND_XCCONFIG="$BUILD_DIR/Brand.generated.xcconfig"
BUILD_ASSETS="$BUILD_DIR/Assets.xcassets"
BUILD_LOCALIZATION_DIR="$BUILD_DIR/Localization"
BUILD_LOTTIE_DIR="$BUILD_DIR/Lottie"

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

list_brand_dirs() {
  find "$SCHEMES_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' | sort
}

brand_name_from_dir() {
  basename "$1"
}

brand_xcconfig_path() {
  expected="$1/$(brand_name_from_dir "$1").xcconfig"
  if [ -f "$expected" ]; then
    printf '%s\n' "$expected"
    return 0
  fi

  find "$1" -maxdepth 1 -type f -name '*.xcconfig' | sort | sed -n '1p'
}

resolve_brand_dir() {
  target="$(lowercase "$1")"

  for brand_dir in $(list_brand_dirs); do
    brand_name="$(brand_name_from_dir "$brand_dir")"
    if [ "$(lowercase "$brand_name")" = "$target" ]; then
      printf '%s\n' "$brand_dir"
      return 0
    fi
  done

  return 1
}

pick_brand() {
  printf '%s\n' "Selecione o scheme:" >&2

  index=1
  for brand_dir in $(list_brand_dirs); do
    brand_name="$(brand_name_from_dir "$brand_dir")"
    printf '%s\n' "$index) $brand_name" >&2
    index=$((index + 1))
  done

  printf '%s' "> " >&2
  read -r choice

  index=1
  for brand_dir in $(list_brand_dirs); do
    if [ "$choice" = "$index" ]; then
      printf '%s\n' "$(brand_name_from_dir "$brand_dir")"
      return 0
    fi
    index=$((index + 1))
  done

  printf '%s\n' "Opcao invalida." >&2
  exit 1
}

if [ "${1-}" != "" ]; then
  BRAND_DIR="$(resolve_brand_dir "$1")" || {
    printf '%s\n' "Brand invalida: $1" >&2
    exit 1
  }
else
  SELECTED_BRAND="$(pick_brand)"
  BRAND_DIR="$(resolve_brand_dir "$SELECTED_BRAND")"
fi

BRAND_NAME="$(brand_name_from_dir "$BRAND_DIR")"
BRAND_XCCONFIG="$(brand_xcconfig_path "$BRAND_DIR")"
SOURCE_LOCALIZATION_DIR="$BRAND_DIR/Localization"
SOURCE_LOTTIE_DIR="$BRAND_DIR/Lottie"

if [ "$BRAND_XCCONFIG" = "" ] || [ ! -f "$BRAND_XCCONFIG" ]; then
  printf '%s\n' "Arquivo de configuracao da brand nao encontrado: $BRAND_XCCONFIG" >&2
  exit 1
fi

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

find "$BRAND_DIR" -mindepth 1 -maxdepth 1 ! -name '.*' -exec cp -R {} "$BUILD_DIR/" \;
mkdir -p "$BUILD_LOCALIZATION_DIR"

if [ -d "$SOURCE_LOTTIE_DIR" ]; then
  rm -rf "$BUILD_LOTTIE_DIR"
  mkdir -p "$BUILD_LOTTIE_DIR"
  find "$SOURCE_LOTTIE_DIR" -mindepth 1 -maxdepth 1 ! -name '.*' -exec cp -R {} "$BUILD_LOTTIE_DIR/" \;
fi

if [ -d "$SOURCE_LOCALIZATION_DIR" ]; then
  find "$BUILD_LOCALIZATION_DIR" -maxdepth 1 -type f -name '*_override.strings' -delete
  find "$SOURCE_LOCALIZATION_DIR" -maxdepth 1 -type f -name '*_override.strings' -exec cp {} "$BUILD_LOCALIZATION_DIR/" \;
fi

for override_file in pt_override.strings en_override.strings
do
  if [ ! -f "$BUILD_LOCALIZATION_DIR/$override_file" ]; then
    printf '%s\n' "// Generated by set-brand.ex" > "$BUILD_LOCALIZATION_DIR/$override_file"
  fi
done

if [ -d "$BUILD_ASSETS" ] && [ ! -f "$BUILD_ASSETS/Contents.json" ]; then
  printf '%s\n' '{"info":{"author":"xcode","version":1}}' > "$BUILD_ASSETS/Contents.json"
fi

{
  printf '%s\n' "// Generated brand configuration."
  printf '%s\n' "// Source: $(basename "$APP_DIR")/Resources/Schemes/$BRAND_NAME/$(basename "$BRAND_XCCONFIG")"
  printf '%s\n' "// Do not edit this file manually."
  printf '\n'
  grep -v '^[[:space:]]*#include[[:space:]]' "$BRAND_XCCONFIG"
} > "$BUILD_BRAND_XCCONFIG"

printf '%s\n' "Build atualizado com a brand: $BRAND_NAME"
printf '%s\n' "Brand config: $BRAND_XCCONFIG"
printf '%s\n' "Build resources: $BUILD_DIR"
printf '%s\n' "Localization: $BUILD_LOCALIZATION_DIR"
printf '%s\n' "Lottie: $BUILD_LOTTIE_DIR"
printf '%s\n' "Generated config: $BUILD_BRAND_XCCONFIG"
